-- ============================================================================
-- College ERP Database Schema for Oracle Cloud Infrastructure (ATP) & APEX
-- Phase 3 - Design the Database
-- ============================================================================

-- 1. Colleges Table (Tenant Configuration)
CREATE TABLE colleges (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_colleges PRIMARY KEY,
    name          VARCHAR2(255) NOT NULL,
    domain        VARCHAR2(100) UNIQUE,
    address       VARCHAR2(500),
    contact_phone VARCHAR2(20),
    contact_email VARCHAR2(150),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. Roles Table
CREATE TABLE roles (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_roles PRIMARY KEY,
    name        VARCHAR2(50) NOT NULL CONSTRAINT uq_role_name UNIQUE,
    description VARCHAR2(255)
);

-- 3. Users Table (Unified accounts across the college tenancy)
CREATE TABLE users (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
    college_id    NUMBER NOT NULL,
    role_id       NUMBER NOT NULL,
    email         VARCHAR2(150) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name    VARCHAR2(100) NOT NULL,
    last_name     VARCHAR2(100) NOT NULL,
    status        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_users_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT uq_user_college_email UNIQUE (college_id, email),
    CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

-- Create index for faster authentication lookup
CREATE INDEX idx_users_auth ON users (email, status);

-- 4. Departments Table
CREATE TABLE departments (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_departments PRIMARY KEY,
    college_id  NUMBER NOT NULL,
    name        VARCHAR2(150) NOT NULL,
    code        VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_departments_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT uq_dept_college_code UNIQUE (college_id, code)
);

-- 5. Courses Table
CREATE TABLE courses (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_courses PRIMARY KEY,
    college_id    NUMBER NOT NULL,
    department_id NUMBER NOT NULL,
    name          VARCHAR2(150) NOT NULL,
    code          VARCHAR2(20) NOT NULL,
    credits       NUMBER(2) DEFAULT 3 NOT NULL,
    CONSTRAINT fk_courses_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_courses_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    CONSTRAINT uq_course_college_code UNIQUE (college_id, code)
);

-- 6. Academic Years Table
CREATE TABLE academic_years (
    id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_academic_years PRIMARY KEY,
    college_id NUMBER NOT NULL,
    name       VARCHAR2(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,
    is_active  CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT fk_academic_years_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT chk_ay_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_ay_dates CHECK (start_date < end_date)
);

-- 7. Students Table
CREATE TABLE students (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_students PRIMARY KEY,
    user_id          NUMBER NOT NULL CONSTRAINT uq_student_user UNIQUE,
    college_id       NUMBER NOT NULL,
    department_id    NUMBER NOT NULL,
    course_id        NUMBER NOT NULL,
    academic_year_id NUMBER NOT NULL,
    admission_number VARCHAR2(50) NOT NULL,
    roll_number      VARCHAR2(50),
    date_of_birth    DATE,
    phone_number     VARCHAR2(20),
    photo_url        VARCHAR2(500),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_students_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_students_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_students_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_students_ay FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
    CONSTRAINT uq_student_admission UNIQUE (college_id, admission_number)
);

-- 8. Faculty Table
CREATE TABLE faculty (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_faculty PRIMARY KEY,
    user_id       NUMBER NOT NULL CONSTRAINT uq_faculty_user UNIQUE,
    college_id    NUMBER NOT NULL,
    department_id NUMBER NOT NULL,
    designation   VARCHAR2(100) NOT NULL,
    qualification VARCHAR2(255) NOT NULL,
    phone_number  VARCHAR2(20),
    CONSTRAINT fk_faculty_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_faculty_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_faculty_dept FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- 9. Admissions Table
CREATE TABLE admissions (
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_admissions PRIMARY KEY,
    college_id   NUMBER NOT NULL,
    first_name   VARCHAR2(100) NOT NULL,
    last_name    VARCHAR2(100) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    phone        VARCHAR2(20),
    course_id    NUMBER NOT NULL,
    status       VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_by  NUMBER,
    remarks      VARCHAR2(500),
    CONSTRAINT fk_admissions_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_admissions_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_admissions_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT chk_admission_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WAITLISTED'))
);

-- 10. Attendance Table
CREATE TABLE attendance (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_attendance PRIMARY KEY,
    student_id      NUMBER NOT NULL,
    course_id       NUMBER NOT NULL,
    faculty_id      NUMBER NOT NULL,
    attendance_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    status          CHAR(1) NOT NULL,
    remarks         VARCHAR2(255),
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
    CONSTRAINT chk_attendance_status CHECK (status IN ('P', 'A', 'L', 'O')), -- Present, Absent, Late, Other
    CONSTRAINT uq_attendance_entry UNIQUE (student_id, course_id, attendance_date)
);

CREATE INDEX idx_attendance_date ON attendance(attendance_date);

-- 11. Timetable Table
CREATE TABLE timetable (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_timetable PRIMARY KEY,
    college_id       NUMBER NOT NULL,
    department_id    NUMBER NOT NULL,
    course_id        NUMBER NOT NULL,
    faculty_id       NUMBER NOT NULL,
    academic_year_id NUMBER NOT NULL,
    day_of_week      NUMBER(1) NOT NULL,
    start_time       VARCHAR2(8) NOT NULL, -- e.g. "09:00"
    end_time         VARCHAR2(8) NOT NULL, -- e.g. "09:50"
    classroom        VARCHAR2(50),
    CONSTRAINT fk_timetable_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_timetable_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_timetable_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_timetable_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id),
    CONSTRAINT fk_timetable_ay FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
    CONSTRAINT chk_timetable_day CHECK (day_of_week BETWEEN 1 AND 7)
);

-- 12. Exams Table
CREATE TABLE exams (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_exams PRIMARY KEY,
    college_id       NUMBER NOT NULL,
    course_id        NUMBER NOT NULL,
    academic_year_id NUMBER NOT NULL,
    name             VARCHAR2(100) NOT NULL,
    exam_date        DATE NOT NULL,
    max_marks        NUMBER(5,2) NOT NULL,
    min_marks        NUMBER(5,2) NOT NULL,
    CONSTRAINT fk_exams_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_exams_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_exams_ay FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE CASCADE
);

-- 13. Marks Table
CREATE TABLE marks (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_marks PRIMARY KEY,
    exam_id        NUMBER NOT NULL,
    student_id     NUMBER NOT NULL,
    marks_obtained NUMBER(5,2) NOT NULL,
    grade          VARCHAR2(5),
    remarks        VARCHAR2(255),
    CONSTRAINT fk_marks_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    CONSTRAINT fk_marks_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_marks_student_exam UNIQUE (exam_id, student_id),
    CONSTRAINT chk_marks_obtained CHECK (marks_obtained >= 0)
);

-- 14. Fee Structure Table
CREATE TABLE fee_structure (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_fee_structure PRIMARY KEY,
    college_id       NUMBER NOT NULL,
    course_id        NUMBER NOT NULL,
    academic_year_id NUMBER NOT NULL,
    fee_type         VARCHAR2(100) NOT NULL, -- e.g. "Tuition", "Library", "Exam", "Hostel"
    amount           NUMBER(12,2) NOT NULL,
    due_date         DATE NOT NULL,
    CONSTRAINT fk_fee_struct_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_fee_struct_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_fee_struct_ay FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE CASCADE,
    CONSTRAINT chk_fee_amount CHECK (amount >= 0)
);

-- 15. Fee Payments Table
CREATE TABLE fee_payments (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_fee_payments PRIMARY KEY,
    student_id       NUMBER NOT NULL,
    fee_structure_id NUMBER NOT NULL,
    amount_paid      NUMBER(12,2) NOT NULL,
    payment_date     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    payment_method   VARCHAR2(50) NOT NULL, -- e.g. "Razorpay", "Card", "NetBanking", "Cash"
    transaction_id   VARCHAR2(100) UNIQUE,
    status           VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
    CONSTRAINT fk_fee_pay_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_fee_pay_struct FOREIGN KEY (fee_structure_id) REFERENCES fee_structure(id) ON DELETE CASCADE,
    CONSTRAINT chk_fee_pay_amount CHECK (amount_paid > 0),
    CONSTRAINT chk_fee_pay_status CHECK (status IN ('COMPLETED', 'PENDING', 'FAILED'))
);

-- 16. Library Books Table
CREATE TABLE library_books (
    id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_library_books PRIMARY KEY,
    college_id NUMBER NOT NULL,
    title      VARCHAR2(255) NOT NULL,
    author     VARCHAR2(255) NOT NULL,
    isbn       VARCHAR2(20),
    quantity   NUMBER(4) DEFAULT 1 NOT NULL,
    available  NUMBER(4) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_lib_books_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT chk_lib_qty CHECK (quantity >= 0),
    CONSTRAINT chk_lib_avail CHECK (available <= quantity AND available >= 0)
);

-- 17. Book Issues Table
CREATE TABLE book_issues (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_book_issues PRIMARY KEY,
    book_id     NUMBER NOT NULL,
    user_id     NUMBER NOT NULL,
    issue_date  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    due_date    DATE NOT NULL,
    return_date DATE,
    fine_amount NUMBER(6,2) DEFAULT 0 NOT NULL,
    status      VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    CONSTRAINT fk_book_issues_book FOREIGN KEY (book_id) REFERENCES library_books(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_issues_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_book_issue_status CHECK (status IN ('ISSUED', 'RETURNED', 'OVERDUE')),
    CONSTRAINT chk_book_dates CHECK (issue_date <= due_date)
);

-- 18. Hostel Rooms Table
CREATE TABLE hostel_rooms (
    id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_hostel_rooms PRIMARY KEY,
    college_id NUMBER NOT NULL,
    block_name VARCHAR2(100) NOT NULL, -- e.g. "Boys Block A"
    room_number VARCHAR2(20) NOT NULL,
    capacity   NUMBER(2) DEFAULT 1 NOT NULL,
    occupied   NUMBER(2) DEFAULT 0 NOT NULL,
    status     VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CONSTRAINT fk_hostel_rooms_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT uq_hostel_room UNIQUE (college_id, block_name, room_number),
    CONSTRAINT chk_hostel_cap CHECK (capacity > 0),
    CONSTRAINT chk_hostel_occ CHECK (occupied <= capacity AND occupied >= 0),
    CONSTRAINT chk_hostel_status CHECK (status IN ('AVAILABLE', 'FULL', 'MAINTENANCE'))
);

-- 19. Transport Routes Table
CREATE TABLE transport_routes (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_transport_routes PRIMARY KEY,
    college_id     NUMBER NOT NULL,
    route_name     VARCHAR2(150) NOT NULL,
    driver_name    VARCHAR2(100),
    driver_phone   VARCHAR2(20),
    vehicle_number VARCHAR2(50),
    CONSTRAINT fk_transport_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE
);

-- 20. Notifications Table
CREATE TABLE notifications (
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_notifications PRIMARY KEY,
    college_id   NUMBER NOT NULL,
    sender_id    NUMBER,
    recipient_id NUMBER NOT NULL,
    title        VARCHAR2(255) NOT NULL,
    message      CLOB NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    is_read      CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_notif_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_notif_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_notif_read CHECK (is_read IN ('Y', 'N'))
);

-- 21. Documents Table (Connects files stored in OCI Object Storage to APEX Records)
CREATE TABLE documents (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_documents PRIMARY KEY,
    college_id      NUMBER NOT NULL,
    uploader_id     NUMBER NOT NULL,
    entity_type     VARCHAR2(50) NOT NULL,
    entity_id       NUMBER NOT NULL,
    file_name       VARCHAR2(255) NOT NULL,
    file_size       NUMBER NOT NULL,
    file_type       VARCHAR2(100),
    oci_object_name VARCHAR2(500) NOT NULL, -- Object Name path inside the OCI Object Storage Bucket
    uploaded_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_docs_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_docs_uploader FOREIGN KEY (uploader_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_doc_entity CHECK (entity_type IN ('STUDENT', 'FACULTY', 'ADMISSION', 'ASSIGNMENT', 'GENERAL'))
);

-- 22. Audit Logs Table (For security auditing)
CREATE TABLE audit_logs (
    id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_audit_logs PRIMARY KEY,
    college_id NUMBER NOT NULL,
    user_id    NUMBER,
    action     VARCHAR2(100) NOT NULL, -- e.g. "CREATE STUDENT", "GRADE_UPDATE", "FEE_PAID"
    table_name VARCHAR2(50) NOT NULL,
    record_id  NUMBER NOT NULL,
    old_values CLOB,
    new_values CLOB,
    logged_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address VARCHAR2(50),
    CONSTRAINT fk_audit_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================================
-- Utility PL/SQL Triggers for Audit Logging & Stock Management
-- ============================================================================

-- Trigger to adjust available library book stock upon checkout or return
CREATE OR REPLACE TRIGGER trg_book_stock_update
AFTER INSERT OR UPDATE ON book_issues
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.status = 'ISSUED' THEN
            UPDATE library_books
            SET available = available - 1
            WHERE id = :NEW.book_id;
        END IF;
    ELSIF UPDATING THEN
        IF :OLD.status = 'ISSUED' AND :NEW.status = 'RETURNED' THEN
            UPDATE library_books
            SET available = available + 1
            WHERE id = :NEW.book_id;
        ELSIF :OLD.status = 'RETURNED' AND :NEW.status = 'ISSUED' THEN
            UPDATE library_books
            SET available = available - 1
            WHERE id = :NEW.book_id;
        END IF;
    END IF;
END;
/

-- Trigger to calculate and update grades automatically in Marks Table based on Marks Obtained
CREATE OR REPLACE TRIGGER trg_auto_grade_calculation
BEFORE INSERT OR UPDATE ON marks
FOR EACH ROW
DECLARE
    v_max_marks NUMBER(5,2);
    v_percentage NUMBER(5,2);
BEGIN
    SELECT max_marks INTO v_max_marks
    FROM exams
    WHERE id = :NEW.exam_id;
    
    IF v_max_marks > 0 THEN
        v_percentage := (:NEW.marks_obtained / v_max_marks) * 100;
        
        IF v_percentage >= 90 THEN
            :NEW.grade := 'A+';
        ELSIF v_percentage >= 80 THEN
            :NEW.grade := 'A';
        ELSIF v_percentage >= 70 THEN
            :NEW.grade := 'B';
        ELSIF v_percentage >= 60 THEN
            :NEW.grade := 'C';
        ELSIF v_percentage >= 50 THEN
            :NEW.grade := 'D';
        ELSE
            :NEW.grade := 'F';
        END IF;
    ELSE
        :NEW.grade := 'I'; -- Incomplete / Invalid
    END IF;
END;
/
