// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in StreamVista user's id, email, and OAuth client id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-titles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function userClient(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_titles_default = defineTool2({
  name: "list_titles",
  title: "List my titles",
  description: "List content titles owned by the signed-in creator. Returns id, title, status, genre, language, and updated_at.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    status: z.string().optional().describe("Optional exact status filter (e.g. 'draft', 'submitted', 'approved').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient(ctx);
    let q = supabase.from("content_titles").select("id, title, status, genre, language, duration_minutes, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { titles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-title.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function userClient2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_title_default = defineTool3({
  name: "get_title",
  title: "Get a title",
  description: "Fetch full details for a single content title by id (RLS-scoped to the signed-in user).",
  inputSchema: { id: z2.string().uuid().describe("The title id (UUID).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient2(ctx).from("content_titles").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { title: data }
    };
  }
});

// src/lib/mcp/tools/list-ingest-jobs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function userClient3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_ingest_jobs_default = defineTool4({
  name: "list_ingest_jobs",
  title: "List ingest jobs",
  description: "List recent Studio ingest jobs visible to the signed-in user (RLS-scoped). Returns status, progress, and workspace/project ids.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    status: z3.string().optional().describe("Optional exact status filter (e.g. 'queued', 'uploading', 'complete', 'failed').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = userClient3(ctx).from("ingest_jobs").select(
      "id, status, job_mode, destination_type, project_id, workspace_id, total_files, completed_files, failed_files, total_bytes, transferred_bytes, started_at, completed_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-productions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_shared.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
function userClient4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauth() {
  return {
    content: [{ type: "text", text: "Please sign in to your StreamVista Studio account." }],
    isError: true
  };
}
function notStudio() {
  return {
    content: [
      {
        type: "text",
        text: "This tool is available to StreamVista Studio users only. Ask your workspace owner for access."
      }
    ],
    isError: true
  };
}
async function getStudioWorkspaceIds(ctx) {
  const sb = userClient4(ctx);
  const uid = ctx.getUserId();
  if (!uid) return [];
  const [owned, member] = await Promise.all([
    sb.from("workspaces").select("id").eq("owner_id", uid),
    sb.from("workspace_members").select("workspace_id").eq("user_id", uid)
  ]);
  const ids = /* @__PURE__ */ new Set();
  (owned.data ?? []).forEach((r) => ids.add(r.id));
  (member.data ?? []).forEach((r) => ids.add(r.workspace_id));
  return Array.from(ids);
}
function notCreator() {
  return {
    content: [
      {
        type: "text",
        text: "This tool is available to StreamVista Creator accounts only. Contact support if you believe you should have access."
      }
    ],
    isError: true
  };
}
async function isCreatorUser(ctx) {
  const uid = ctx.getUserId();
  if (!uid) return false;
  const { data } = await userClient4(ctx).from("user_roles").select("role").eq("user_id", uid);
  const roles = (data ?? []).map((r) => r.role);
  return roles.includes("content_owner") || roles.includes("creator");
}
function formatBytes(bytes) {
  if (!bytes || bytes <= 0) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let v = bytes;
  let i = 0;
  while (v >= 1024 && i < units.length - 1) {
    v /= 1024;
    i++;
  }
  return `${v.toFixed(v >= 100 ? 0 : 1)} ${units[i]}`;
}
function ok(structured, summary) {
  return {
    content: [{ type: "text", text: summary }],
    structuredContent: structured
  };
}

// src/lib/mcp/tools/list-productions.ts
var list_productions_default = defineTool5({
  name: "list_productions",
  title: "List productions",
  description: "List the signed-in Studio user's active productions across their studio workspaces. Returns each production's name, title number, banner, and last-updated time.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max productions to return (default 25)."),
    search: z4.string().optional().describe("Optional case-insensitive substring match on production name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    let q = userClient4(ctx).from("projects").select("id, name, description, workspace_id, production_banner, crew, updated_at, created_at").in("workspace_id", wsIds).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not load productions right now." }], isError: true };
    const productions = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description ?? null,
      title_number: p.crew?.title_number ?? null,
      banner: p.production_banner ?? p.crew?.production_house ?? null,
      last_updated: p.updated_at
    }));
    return ok(
      { productions, total: productions.length },
      productions.length ? `Found ${productions.length} production${productions.length === 1 ? "" : "s"}.` : "No productions yet in your studio workspace."
    );
  }
});

// src/lib/mcp/tools/open-production.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var open_production_default = defineTool6({
  name: "open_production",
  title: "Open production",
  description: "Open a single production and return its overview: name, banner, title number, team crew summary, active ingest jobs, and asset totals. Studio-scoped by RLS.",
  inputSchema: {
    id: z5.string().uuid().describe("The production id (UUID) from `list_productions`.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const sb = userClient4(ctx);
    const { data: p, error } = await sb.from("projects").select("id, name, description, workspace_id, production_banner, crew, created_at, updated_at").eq("id", id).maybeSingle();
    if (error || !p) return { content: [{ type: "text", text: "Production not found or access denied." }], isError: true };
    const [jobs, assets] = await Promise.all([
      sb.from("ingest_jobs").select("id, status, total_files, completed_files, transferred_bytes, total_bytes, updated_at").eq("project_id", id).order("updated_at", { ascending: false }).limit(5),
      sb.from("studio_assets").select("id, total_size_bytes", { count: "exact" }).eq("project_id", id)
    ]);
    const assetCount = assets.count ?? (assets.data?.length ?? 0);
    const totalBytes = (assets.data ?? []).reduce(
      (n, a) => n + (Number(a.total_size_bytes) || 0),
      0
    );
    return ok(
      {
        production: {
          id: p.id,
          name: p.name,
          description: p.description ?? null,
          banner: p.production_banner ?? p.crew?.production_house ?? null,
          title_number: p.crew?.title_number ?? null,
          crew: p.crew ?? {},
          last_updated: p.updated_at
        },
        recent_uploads: jobs.data ?? [],
        asset_totals: { count: assetCount, total_bytes: totalBytes }
      },
      `Opened production "${p.name}".`
    );
  }
});

// src/lib/mcp/tools/show-todays-work.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
var show_todays_work_default = defineTool7({
  name: "show_todays_work",
  title: "Show today's work",
  description: "Summarize what the signed-in Studio user should do next today: unread alerts, in-flight uploads, and deliveries awaiting action.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const sb = userClient4(ctx);
    const uid = ctx.getUserId();
    const [notifs, active, pendingDeliveries] = await Promise.all([
      sb.from("notifications").select("id, title, message, is_read, created_at").eq("user_id", uid).eq("is_read", false).order("created_at", { ascending: false }).limit(10),
      sb.from("ingest_jobs").select("id, status, total_files, completed_files, updated_at, project_id").in("workspace_id", wsIds).in("status", ["queued", "uploading", "processing", "verifying"]).order("updated_at", { ascending: false }).limit(10),
      sb.from("deal_deliveries").select("id, status, recipient_email, buyer_org_name, updated_at").in("status", ["pending", "in_progress", "shared"]).order("updated_at", { ascending: false }).limit(10)
    ]);
    const tasks = [];
    (notifs.data ?? []).forEach(
      (n) => tasks.push({ kind: "alert", label: n.title || n.message || "New alert", id: n.id })
    );
    (active.data ?? []).forEach(
      (j) => tasks.push({
        kind: "upload",
        label: `Upload in progress \xB7 ${j.completed_files ?? 0}/${j.total_files ?? 0} files`,
        id: j.id
      })
    );
    (pendingDeliveries.data ?? []).forEach(
      (d) => tasks.push({
        kind: "delivery",
        label: `Delivery to ${d.buyer_org_name ?? d.recipient_email ?? "buyer"} \xB7 ${d.status}`,
        id: d.id
      })
    );
    return ok(
      {
        unread_alerts: notifs.data ?? [],
        active_uploads: active.data ?? [],
        pending_deliveries: pendingDeliveries.data ?? [],
        tasks
      },
      tasks.length ? `You have ${tasks.length} item${tasks.length === 1 ? "" : "s"} needing attention today.` : "You're all caught up \u2014 no pending items today."
    );
  }
});

// src/lib/mcp/tools/show-upload-progress.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
var show_upload_progress_default = defineTool8({
  name: "show_upload_progress",
  title: "Show upload progress",
  description: "Show current and recent media uploads for the signed-in Studio user, with human-readable progress and transfer size.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).optional().describe("Max uploads to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const { data, error } = await userClient4(ctx).from("ingest_jobs").select(
      "id, status, total_files, completed_files, failed_files, total_bytes, transferred_bytes, started_at, completed_at, updated_at, project_id"
    ).in("workspace_id", wsIds).order("updated_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: "Could not load upload progress." }], isError: true };
    const uploads = (data ?? []).map((j) => {
      const pct = j.total_files && j.total_files > 0 ? Math.round(100 * (j.completed_files ?? 0) / j.total_files) : 0;
      return {
        id: j.id,
        status: j.status,
        files_completed: j.completed_files ?? 0,
        files_total: j.total_files ?? 0,
        files_failed: j.failed_files ?? 0,
        percent_complete: pct,
        transferred: formatBytes(j.transferred_bytes),
        total_size: formatBytes(j.total_bytes),
        started_at: j.started_at,
        completed_at: j.completed_at
      };
    });
    return ok(
      { uploads },
      uploads.length ? `Showing ${uploads.length} upload${uploads.length === 1 ? "" : "s"}.` : "No uploads yet."
    );
  }
});

// src/lib/mcp/tools/show-storage-usage.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
var show_storage_usage_default = defineTool9({
  name: "show_storage_usage",
  title: "Show storage usage",
  description: "Report the signed-in Studio user's storage plan, allocated capacity, used capacity, and remaining headroom.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const sb = userClient4(ctx);
    const [ent, usage] = await Promise.all([
      sb.from("workspace_storage_entitlements").select("workspace_id, plan_code, total_storage_gb, included_storage_gb, paid_storage_gb, admin_bonus_storage_gb, billing_status").in("workspace_id", wsIds),
      sb.from("workspace_storage_usage").select("workspace_id, billable_bytes, display_used_bytes, last_recalculated_at").in("workspace_id", wsIds)
    ]);
    const usageByWs = /* @__PURE__ */ new Map();
    (usage.data ?? []).forEach((u) => usageByWs.set(u.workspace_id, u));
    const workspaces = (ent.data ?? []).map((e) => {
      const u = usageByWs.get(e.workspace_id);
      const usedBytes = Number(u?.display_used_bytes ?? u?.billable_bytes ?? 0);
      const totalBytes = Number(e.total_storage_gb ?? 0) * 1024 ** 3;
      const remaining = Math.max(0, totalBytes - usedBytes);
      const pct = totalBytes > 0 ? Math.round(100 * usedBytes / totalBytes) : 0;
      return {
        workspace_id: e.workspace_id,
        plan: e.plan_code,
        total: formatBytes(totalBytes),
        used: formatBytes(usedBytes),
        available: formatBytes(remaining),
        percent_used: pct,
        billing_status: e.billing_status
      };
    });
    return ok({ workspaces }, workspaces.length ? "Storage summary ready." : "No storage plan is active yet.");
  }
});

// src/lib/mcp/tools/show-recent-activity.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
var show_recent_activity_default = defineTool10({
  name: "show_recent_activity",
  title: "Show recent activity",
  description: "Show the signed-in Studio user's recent notifications and activity feed.",
  inputSchema: {
    limit: z7.number().int().min(1).max(100).optional().describe("Max entries (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const { data, error } = await userClient4(ctx).from("notifications").select("id, title, message, is_read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: "Could not load recent activity." }], isError: true };
    return ok({ activity: data ?? [] }, `Recent activity: ${(data ?? []).length} entries.`);
  }
});

// src/lib/mcp/tools/show-team.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
var show_team_default = defineTool11({
  name: "show_team",
  title: "Show team",
  description: "List the signed-in Studio user's team members across their workspaces, including each member's role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const sb = userClient4(ctx);
    const { data: members, error } = await sb.from("workspace_members").select("workspace_id, user_id, role, created_at").in("workspace_id", wsIds);
    if (error) return { content: [{ type: "text", text: "Could not load team members." }], isError: true };
    const userIds = Array.from(new Set((members ?? []).map((m) => m.user_id)));
    let profiles = [];
    if (userIds.length > 0) {
      const { data: profs } = await sb.from("user_profiles").select("id, display_name, email, avatar_url").in("id", userIds);
      profiles = profs ?? [];
    }
    const byId = new Map(profiles.map((p) => [p.id, p]));
    const team = (members ?? []).map((m) => {
      const p = byId.get(m.user_id) ?? {};
      return {
        workspace_id: m.workspace_id,
        role: m.role,
        name: p.display_name ?? null,
        email: p.email ?? null,
        joined_at: m.created_at
      };
    });
    return ok(
      { team, total: team.length },
      team.length ? `Your team has ${team.length} member${team.length === 1 ? "" : "s"}.` : "No team members yet."
    );
  }
});

// src/lib/mcp/tools/show-deliveries.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25.76";
var show_deliveries_default = defineTool12({
  name: "show_deliveries",
  title: "Show deliveries",
  description: "List the signed-in Studio user's recent buyer deliveries, including recipient, delivery status, and share expiry.",
  inputSchema: {
    limit: z8.number().int().min(1).max(100).optional().describe("Max deliveries to return (default 20)."),
    status: z8.string().optional().describe("Optional exact status filter (e.g. 'pending', 'shared', 'delivered').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    let q = userClient4(ctx).from("deal_deliveries").select(
      "id, status, method, buyer_org_name, recipient_email, share_url, expires_at, shared_at, delivered_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not load deliveries." }], isError: true };
    return ok(
      { deliveries: data ?? [] },
      (data ?? []).length ? `Showing ${data.length} deliver${data.length === 1 ? "y" : "ies"}.` : "No deliveries yet."
    );
  }
});

// src/lib/mcp/tools/show-billing.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25.76";
function money(paise, currency) {
  if (paise == null) return "";
  const amount = paise / 100;
  const cur = (currency || "INR").toUpperCase();
  const symbol = cur === "INR" ? "\u20B9" : cur === "USD" ? "$" : cur === "EUR" ? "\u20AC" : `${cur} `;
  return `${symbol}${amount.toFixed(2)}`;
}
var show_billing_default = defineTool13({
  name: "show_billing",
  title: "Show billing",
  description: "Summarize the signed-in Studio user's recent invoices, showing invoice number, amount, currency, status, and issued date.",
  inputSchema: {
    limit: z9.number().int().min(1).max(100).optional().describe("Max invoices to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    const { data, error } = await userClient4(ctx).from("invoices").select("id, invoice_number, description, currency, total_paise, status, issued_at, source").eq("user_id", ctx.getUserId()).order("issued_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: "Could not load billing history." }], isError: true };
    const invoices = (data ?? []).map((r) => ({
      id: r.id,
      number: r.invoice_number,
      description: r.description,
      amount: money(r.total_paise, r.currency),
      currency: r.currency,
      status: r.status,
      issued_at: r.issued_at,
      source: r.source
    }));
    const outstanding = invoices.filter((i) => i.status && i.status !== "paid" && i.status !== "refunded").length;
    return ok(
      { invoices, outstanding_count: outstanding },
      invoices.length ? `${invoices.length} invoice${invoices.length === 1 ? "" : "s"}${outstanding ? `, ${outstanding} still open` : ""}.` : "No billing history yet."
    );
  }
});

// src/lib/mcp/tools/search-files.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.25.76";
var search_files_default = defineTool14({
  name: "search_files",
  title: "Search files",
  description: "Search the signed-in Studio user's media library by file title. Returns matching assets with size, camera info, and shoot date.",
  inputSchema: {
    query: z10.string().min(1).describe("Substring to match against the file title (case-insensitive)."),
    limit: z10.number().int().min(1).max(100).optional().describe("Max results (default 25)."),
    production_id: z10.string().uuid().optional().describe("Optional: limit results to a specific production.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, production_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const wsIds = await getStudioWorkspaceIds(ctx);
    if (wsIds.length === 0) return notStudio();
    let q = userClient4(ctx).from("studio_assets").select(
      "id, title, asset_type, total_size_bytes, file_count, camera_make, camera_model, codec, resolution, fps, shoot_date, status, project_id, workspace_id, updated_at"
    ).in("workspace_id", wsIds).ilike("title", `%${query}%`).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (production_id) q = q.eq("project_id", production_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not search your media library." }], isError: true };
    const files = (data ?? []).map((a) => ({
      id: a.id,
      title: a.title,
      type: a.asset_type,
      size: formatBytes(a.total_size_bytes),
      file_count: a.file_count,
      camera: [a.camera_make, a.camera_model].filter(Boolean).join(" ") || null,
      codec: a.codec,
      resolution: a.resolution,
      fps: a.fps,
      shoot_date: a.shoot_date,
      status: a.status,
      production_id: a.project_id
    }));
    return ok(
      { files, total: files.length, query },
      files.length ? `Found ${files.length} file${files.length === 1 ? "" : "s"} matching "${query}".` : `No files match "${query}".`
    );
  }
});

// src/lib/mcp/tools/creator-my-workspace.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
var creator_my_workspace_default = defineTool15({
  name: "creator_my_workspace",
  title: "My workspace",
  description: "Overview of the signed-in Creator's workspace: total titles, titles by review stage, and active distribution offers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const uid = ctx.getUserId();
    const sb = userClient4(ctx);
    const [titles, offers] = await Promise.all([
      sb.from("content_titles").select("id, status").eq("owner_user_id", uid),
      sb.from("distribution_program_offers").select("id, status").eq("creator_user_id", uid)
    ]);
    if (titles.error || offers.error) {
      return { content: [{ type: "text", text: "Could not load your workspace summary." }], isError: true };
    }
    const byStatus = {};
    (titles.data ?? []).forEach((t) => {
      const s = t.status || "draft";
      byStatus[s] = (byStatus[s] ?? 0) + 1;
    });
    const activeOffers = (offers.data ?? []).filter(
      (o) => o.status && o.status !== "rejected" && o.status !== "expired"
    ).length;
    return ok(
      {
        total_titles: (titles.data ?? []).length,
        titles_by_status: byStatus,
        active_distribution_offers: activeOffers
      },
      `You have ${(titles.data ?? []).length} title${(titles.data ?? []).length === 1 ? "" : "s"} and ${activeOffers} active distribution offer${activeOffers === 1 ? "" : "s"}.`
    );
  }
});

// src/lib/mcp/tools/creator-list-titles.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.25.76";
var creator_list_titles_default = defineTool16({
  name: "creator_list_titles",
  title: "List my titles",
  description: "List the signed-in Creator's titles with title, status, genre, language, duration, and last-updated time.",
  inputSchema: {
    limit: z11.number().int().min(1).max(100).optional().describe("Max rows to return (default 25)."),
    status: z11.string().optional().describe("Optional exact status filter (e.g. 'draft', 'submitted', 'approved').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    let q = userClient4(ctx).from("content_titles").select("id, title, status, genre, language, duration_minutes, updated_at").eq("owner_user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not load your titles." }], isError: true };
    return ok(
      { titles: data ?? [], total: (data ?? []).length },
      (data ?? []).length ? `Showing ${data.length} title${data.length === 1 ? "" : "s"}.` : "No titles yet."
    );
  }
});

// src/lib/mcp/tools/creator-open-title.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.25.76";
var creator_open_title_default = defineTool17({
  name: "creator_open_title",
  title: "Open a title",
  description: "Open one of the signed-in Creator's titles by id and return its core details, current status, and last-updated time.",
  inputSchema: { id: z12.string().uuid().describe("The title id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const { data, error } = await userClient4(ctx).from("content_titles").select(
      "id, title, status, genre, language, duration_minutes, synopsis, submitted_at, approved_at, published_at, updated_at, created_at"
    ).eq("id", id).eq("owner_user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: "Could not open that title." }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Title not found in your workspace." }], isError: true };
    return ok({ title: data }, `${data.title} \u2014 status: ${data.status ?? "draft"}.`);
  }
});

// src/lib/mcp/tools/creator-submission-status.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.25.76";
var creator_submission_status_default = defineTool18({
  name: "creator_submission_status",
  title: "Submission status",
  description: "Show the review/approval status of the signed-in Creator's titles, grouped by stage, and list the most recently updated titles.",
  inputSchema: {
    limit: z13.number().int().min(1).max(100).optional().describe("Max recent titles to list (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const { data, error } = await userClient4(ctx).from("content_titles").select("id, title, status, submitted_at, approved_at, published_at, updated_at").eq("owner_user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: "Could not load submission status." }], isError: true };
    const buckets = {};
    (data ?? []).forEach((t) => {
      const s = t.status || "draft";
      buckets[s] = (buckets[s] ?? 0) + 1;
    });
    return ok(
      { by_stage: buckets, recent: data ?? [] },
      `Reviewed ${(data ?? []).length} recent title${(data ?? []).length === 1 ? "" : "s"}.`
    );
  }
});

// src/lib/mcp/tools/creator-rights-status.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^3.25.76";
var creator_rights_status_default = defineTool19({
  name: "creator_rights_status",
  title: "Rights status",
  description: "Show rights availability for one of the signed-in Creator's titles: territory, language, category, exclusivity, term dates, and current status.",
  inputSchema: {
    title_id: z14.string().uuid().describe("The title id to inspect."),
    limit: z14.number().int().min(1).max(200).optional().describe("Max rights rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ title_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const sb = userClient4(ctx);
    const owner = await sb.from("content_titles").select("id, title").eq("id", title_id).eq("owner_user_id", ctx.getUserId()).maybeSingle();
    if (owner.error || !owner.data) {
      return { content: [{ type: "text", text: "Title not found in your workspace." }], isError: true };
    }
    const { data, error } = await sb.from("title_rights_availability").select("id, right_category, territory, language, exclusivity, status, term_start, term_end, notes, updated_at").eq("title_id", title_id).order("updated_at", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: "Could not load rights availability." }], isError: true };
    return ok(
      { title: owner.data.title, rights: data ?? [] },
      (data ?? []).length ? `${(data ?? []).length} rights entr${(data ?? []).length === 1 ? "y" : "ies"} on "${owner.data.title}".` : `No rights configured yet on "${owner.data.title}".`
    );
  }
});

// src/lib/mcp/tools/creator-list-assets.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^3.25.76";
var creator_list_assets_default = defineTool20({
  name: "creator_list_assets",
  title: "List title assets",
  description: "List the files (masters, artwork, subtitles, etc.) attached to one of the signed-in Creator's titles.",
  inputSchema: {
    title_id: z15.string().uuid().describe("The title id."),
    limit: z15.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ title_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const sb = userClient4(ctx);
    const owner = await sb.from("content_titles").select("id, title").eq("id", title_id).eq("owner_user_id", ctx.getUserId()).maybeSingle();
    if (owner.error || !owner.data) {
      return { content: [{ type: "text", text: "Title not found in your workspace." }], isError: true };
    }
    const { data, error } = await sb.from("title_assets").select(
      "id, category, is_primary, created_at, upload:recent_uploads(id, file_name, file_size, mime_type, status, created_at)"
    ).eq("title_id", title_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: "Could not load assets for that title." }], isError: true };
    const assets = (data ?? []).map((row) => ({
      id: row.id,
      category: row.category,
      is_primary: row.is_primary,
      file_name: row.upload?.file_name ?? null,
      file_size: formatBytes(row.upload?.file_size ?? null),
      file_type: row.upload?.mime_type ?? null,
      upload_status: row.upload?.status ?? null,
      added_at: row.created_at
    }));
    return ok(
      { title: owner.data.title, assets },
      assets.length ? `${assets.length} file${assets.length === 1 ? "" : "s"} on "${owner.data.title}".` : `No files attached yet on "${owner.data.title}".`
    );
  }
});

// src/lib/mcp/tools/creator-review-notes.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z16 } from "npm:zod@^3.25.76";
var creator_review_notes_default = defineTool21({
  name: "creator_review_notes",
  title: "Review notes",
  description: "Latest review notes posted by the review team on the signed-in Creator's titles. Includes the review decision and the note text.",
  inputSchema: {
    limit: z16.number().int().min(1).max(100).optional().describe("Max notes (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const sb = userClient4(ctx);
    const titles = await sb.from("content_titles").select("id, title").eq("owner_user_id", ctx.getUserId());
    if (titles.error) return { content: [{ type: "text", text: "Could not load your titles." }], isError: true };
    const titleIds = (titles.data ?? []).map((t) => t.id);
    if (titleIds.length === 0) return ok({ notes: [] }, "No review notes yet.");
    const titleMap = new Map((titles.data ?? []).map((t) => [t.id, t.title]));
    const { data, error } = await sb.from("content_approvals").select("id, title_id, to_status, note, created_at").in("title_id", titleIds).not("note", "is", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: "Could not load review notes." }], isError: true };
    const notes = (data ?? []).map((r) => ({
      id: r.id,
      title_id: r.title_id,
      title: titleMap.get(r.title_id) ?? "Untitled",
      decision: r.to_status,
      note: r.note,
      posted_at: r.created_at
    }));
    return ok(
      { notes },
      notes.length ? `${notes.length} review note${notes.length === 1 ? "" : "s"} from the review team.` : "No review notes yet."
    );
  }
});

// src/lib/mcp/tools/creator-distribution-status.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z17 } from "npm:zod@^3.25.76";
var creator_distribution_status_default = defineTool22({
  name: "creator_distribution_status",
  title: "Distribution status",
  description: "List distribution program offers held by the signed-in Creator, showing program name, term, revenue split, and current status.",
  inputSchema: {
    status: z17.string().optional().describe("Optional exact status filter (e.g. 'offered', 'accepted', 'rejected')."),
    limit: z17.number().int().min(1).max(100).optional().describe("Max offers (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    let q = userClient4(ctx).from("distribution_program_offers").select(
      "id, program_name, status, revenue_model, rights_holder_share_pct, streamvista_share_pct, term_years, term_start_date, term_end_date, is_non_exclusive, offered_at, accepted_at, rejected_at, title_id, updated_at"
    ).eq("creator_user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not load distribution offers." }], isError: true };
    return ok(
      { offers: data ?? [] },
      (data ?? []).length ? `Showing ${data.length} distribution offer${data.length === 1 ? "" : "s"}.` : "No distribution offers yet."
    );
  }
});

// src/lib/mcp/tools/creator-storage-usage.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.20.0";
var GB = 1024 ** 3;
var creator_storage_usage_default = defineTool23({
  name: "creator_storage_usage",
  title: "Storage usage",
  description: "Report the signed-in Creator's storage plan, allocated capacity, used capacity, and remaining headroom.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const sb = userClient4(ctx);
    const uid = ctx.getUserId();
    const [entRes, usageRes] = await Promise.all([
      sb.from("workspace_storage_entitlements").select("plan_code, total_storage_gb, included_storage_gb, paid_storage_gb, admin_bonus_storage_gb, billing_status, effective_from").eq("user_id", uid).order("effective_from", { ascending: false }).limit(1).maybeSingle(),
      sb.from("workspace_storage_usage").select("display_used_bytes, active_bytes, archived_bytes, last_recalculated_at").eq("user_id", uid).order("last_recalculated_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    const ent = entRes.data;
    const usage = usageRes.data;
    if (!ent && !usage) {
      return ok({ configured: false }, "No storage plan is active on your account yet.");
    }
    const totalBytes = Number(ent?.total_storage_gb ?? 0) * GB;
    const usedBytes = Number(usage?.display_used_bytes ?? 0);
    const remaining = Math.max(0, totalBytes - usedBytes);
    const pct = totalBytes > 0 ? Math.round(100 * usedBytes / totalBytes) : 0;
    return ok(
      {
        plan: ent?.plan_code ?? null,
        billing_status: ent?.billing_status ?? null,
        total: formatBytes(totalBytes),
        used: formatBytes(usedBytes),
        available: formatBytes(remaining),
        archived: formatBytes(Number(usage?.archived_bytes ?? 0)),
        percent_used: pct
      },
      `${formatBytes(usedBytes)} of ${formatBytes(totalBytes)} used (${pct}%).`
    );
  }
});

// src/lib/mcp/tools/creator-notifications.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z18 } from "npm:zod@^3.25.76";
var creator_notifications_default = defineTool24({
  name: "creator_notifications",
  title: "Notifications",
  description: "Recent notifications for the signed-in Creator, newest first, including whether each has been read.",
  inputSchema: {
    limit: z18.number().int().min(1).max(100).optional().describe("Max notifications (default 20)."),
    unread_only: z18.boolean().optional().describe("If true, only unread notifications are returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    let q = userClient4(ctx).from("notifications").select("id, title, message, is_read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: "Could not load notifications." }], isError: true };
    const unread = (data ?? []).filter((n) => !n.is_read).length;
    return ok(
      { notifications: data ?? [], unread_count: unread },
      (data ?? []).length ? `${(data ?? []).length} notification${(data ?? []).length === 1 ? "" : "s"} (${unread} unread).` : "No notifications yet."
    );
  }
});

// src/lib/mcp/tools/creator-search-my-titles.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z19 } from "npm:zod@^3.25.76";
var creator_search_my_titles_default = defineTool25({
  name: "creator_search_my_titles",
  title: "Search my titles",
  description: "Search the signed-in Creator's titles by name (case-insensitive substring). Returns id, title, status, genre, and last-updated time.",
  inputSchema: {
    query: z19.string().min(1).describe("Substring to match against title name."),
    limit: z19.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    if (!await isCreatorUser(ctx)) return notCreator();
    const { data, error } = await userClient4(ctx).from("content_titles").select("id, title, status, genre, language, updated_at").eq("owner_user_id", ctx.getUserId()).ilike("title", `%${query}%`).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: "Could not search your titles." }], isError: true };
    return ok(
      { titles: data ?? [], total: (data ?? []).length, query },
      (data ?? []).length ? `${(data ?? []).length} title${(data ?? []).length === 1 ? "" : "s"} match "${query}".` : `No titles match "${query}".`
    );
  }
});

// src/lib/mcp/index.ts
var projectRef = "hllgmkfqgeuqlmpcirvn";
var mcp_default = defineMcp({
  name: "streamvista-mcp",
  title: "StreamVista Cloud X",
  version: "0.3.0",
  instructions: "Tools for a signed-in StreamVista Cloud X user. Creator Workspace tools (Creator accounts only): `creator_my_workspace`, `creator_list_titles`, `creator_open_title`, `creator_submission_status`, `creator_rights_status`, `creator_list_assets`, `creator_review_notes`, `creator_distribution_status`, `creator_storage_usage`, `creator_notifications`, `creator_search_my_titles`. Studio Workspace tools (Studio accounts only): `list_productions`, `open_production`, `show_todays_work`, `show_upload_progress`, `show_storage_usage`, `show_recent_activity`, `show_team`, `show_deliveries`, `show_billing`, `search_files`. Legacy read tools kept for compatibility: `list_titles`, `get_title`, `list_ingest_jobs`. Tools that are not available to the caller's role return a friendly access message instead of data. Use `whoami` to verify identity. All data is scoped to the signed-in user via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    // Creator Workspace
    creator_my_workspace_default,
    creator_list_titles_default,
    creator_open_title_default,
    creator_submission_status_default,
    creator_rights_status_default,
    creator_list_assets_default,
    creator_review_notes_default,
    creator_distribution_status_default,
    creator_storage_usage_default,
    creator_notifications_default,
    creator_search_my_titles_default,
    // Studio Workspace
    list_productions_default,
    open_production_default,
    show_todays_work_default,
    show_upload_progress_default,
    show_storage_usage_default,
    show_recent_activity_default,
    show_team_default,
    show_deliveries_default,
    show_billing_default,
    search_files_default,
    // Legacy read tools
    list_titles_default,
    get_title_default,
    list_ingest_jobs_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
