
-- ============ ENUMS ============
DO $$ BEGIN
  CREATE TYPE public.distribution_protocol AS ENUM ('api','ftp','sftp','aspera','signiant','s3','http_webhook');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.distribution_package_status AS ENUM ('draft','building','ready','archived','failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.distribution_queue_status AS ENUM ('queued','dispatching','delivered','failed','cancelled','retrying');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============ PARTNERS ============
CREATE TABLE IF NOT EXISTS public.distribution_partners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  protocol public.distribution_protocol NOT NULL,
  description text,
  contact_email text,
  is_active boolean NOT NULL DEFAULT true,
  requires_aspera boolean NOT NULL DEFAULT false,
  requires_signiant boolean NOT NULL DEFAULT false,
  -- connection config: {host, port, path, region, bucket, endpoint_url, auth_ref, aspera_node, ...}
  -- credentials themselves live in Vault/secrets, referenced by auth_ref, never stored here.
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- default delivery template
  default_package_type text NOT NULL DEFAULT 'imf',
  supported_package_types text[] NOT NULL DEFAULT ARRAY['imf','prores','mp4','xml_only'],
  delivery_window jsonb,
  logo_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.distribution_partners TO authenticated;
GRANT ALL ON public.distribution_partners TO service_role;
ALTER TABLE public.distribution_partners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "read active partners" ON public.distribution_partners
  FOR SELECT TO authenticated USING (is_active OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "admin manage partners" ON public.distribution_partners
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));

-- ============ METADATA MAPPINGS ============
CREATE TABLE IF NOT EXISTS public.distribution_metadata_mappings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL REFERENCES public.distribution_partners(id) ON DELETE CASCADE,
  source_field text NOT NULL, -- e.g. 'title.title', 'meta.genres', 'media_version.codec'
  target_field text NOT NULL, -- e.g. 'ProgramTitle', 'Genre'
  transform text,             -- optional transform id: 'upper','join_semicolon','iso639_2b',...
  default_value text,
  is_required boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (partner_id, target_field)
);

GRANT SELECT ON public.distribution_metadata_mappings TO authenticated;
GRANT ALL ON public.distribution_metadata_mappings TO service_role;
ALTER TABLE public.distribution_metadata_mappings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "read mappings" ON public.distribution_metadata_mappings
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin manage mappings" ON public.distribution_metadata_mappings
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));

-- ============ PACKAGES ============
CREATE TABLE IF NOT EXISTS public.distribution_packages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title_id uuid NOT NULL REFERENCES public.content_titles(id) ON DELETE CASCADE,
  workspace_id uuid,
  owner_user_id uuid NOT NULL DEFAULT auth.uid(),
  package_type text NOT NULL DEFAULT 'imf', -- imf | prores | mp4 | xml_only | custom
  status public.distribution_package_status NOT NULL DEFAULT 'draft',
  -- included pieces from EXISTING tables — no duplication.
  included_media_version_ids uuid[] NOT NULL DEFAULT '{}',
  included_asset_ids uuid[] NOT NULL DEFAULT '{}',
  included_localization_ids uuid[] NOT NULL DEFAULT '{}',
  manifest jsonb NOT NULL DEFAULT '{}'::jsonb, -- generated by packaging engine
  size_bytes bigint NOT NULL DEFAULT 0,
  checksum text,
  build_error text,
  built_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS distribution_packages_title_idx ON public.distribution_packages(title_id);
CREATE INDEX IF NOT EXISTS distribution_packages_status_idx ON public.distribution_packages(status);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.distribution_packages TO authenticated;
GRANT ALL ON public.distribution_packages TO service_role;
ALTER TABLE public.distribution_packages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "owner or admin read packages" ON public.distribution_packages
  FOR SELECT TO authenticated USING (
    owner_user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );
CREATE POLICY "owner or admin write packages" ON public.distribution_packages
  FOR ALL TO authenticated
  USING (
    owner_user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  )
  WITH CHECK (
    owner_user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );

-- ============ QUEUE ============
CREATE TABLE IF NOT EXISTS public.distribution_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL REFERENCES public.distribution_packages(id) ON DELETE CASCADE,
  partner_id uuid NOT NULL REFERENCES public.distribution_partners(id) ON DELETE RESTRICT,
  title_id uuid NOT NULL REFERENCES public.content_titles(id) ON DELETE CASCADE,
  status public.distribution_queue_status NOT NULL DEFAULT 'queued',
  priority int NOT NULL DEFAULT 100,
  attempts int NOT NULL DEFAULT 0,
  max_attempts int NOT NULL DEFAULT 5,
  next_retry_at timestamptz,
  last_error text,
  last_error_code text,
  correlation_id text,
  requested_by uuid DEFAULT auth.uid(),
  dispatched_at timestamptz,
  delivered_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS distribution_queue_status_idx ON public.distribution_queue(status, next_retry_at);
CREATE INDEX IF NOT EXISTS distribution_queue_title_idx ON public.distribution_queue(title_id);

GRANT SELECT, INSERT, UPDATE ON public.distribution_queue TO authenticated;
GRANT ALL ON public.distribution_queue TO service_role;
ALTER TABLE public.distribution_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "owner or admin read queue" ON public.distribution_queue
  FOR SELECT TO authenticated USING (
    requested_by = auth.uid()
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );
CREATE POLICY "owner enqueue" ON public.distribution_queue
  FOR INSERT TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );
CREATE POLICY "owner or admin update queue" ON public.distribution_queue
  FOR UPDATE TO authenticated
  USING (
    requested_by = auth.uid()
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );

-- ============ DELIVERIES (per-partner attempts) ============
CREATE TABLE IF NOT EXISTS public.distribution_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  queue_id uuid NOT NULL REFERENCES public.distribution_queue(id) ON DELETE CASCADE,
  package_id uuid NOT NULL REFERENCES public.distribution_packages(id) ON DELETE CASCADE,
  partner_id uuid NOT NULL REFERENCES public.distribution_partners(id) ON DELETE RESTRICT,
  title_id uuid NOT NULL REFERENCES public.content_titles(id) ON DELETE CASCADE,
  attempt_no int NOT NULL DEFAULT 1,
  protocol public.distribution_protocol NOT NULL,
  status text NOT NULL DEFAULT 'pending', -- pending | in_progress | ok | failed
  transport_response jsonb NOT NULL DEFAULT '{}'::jsonb,
  ack_reference text,
  bytes_transferred bigint NOT NULL DEFAULT 0,
  duration_ms int,
  correlation_id text,
  dispatched_at timestamptz,
  delivered_at timestamptz,
  failed_at timestamptz,
  error_code text,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS distribution_deliveries_queue_idx ON public.distribution_deliveries(queue_id);
CREATE INDEX IF NOT EXISTS distribution_deliveries_title_idx ON public.distribution_deliveries(title_id);

GRANT SELECT, INSERT, UPDATE ON public.distribution_deliveries TO authenticated;
GRANT ALL ON public.distribution_deliveries TO service_role;
ALTER TABLE public.distribution_deliveries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "owner or admin read deliveries" ON public.distribution_deliveries
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );

-- ============ DELIVERY LOGS ============
CREATE TABLE IF NOT EXISTS public.distribution_delivery_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  delivery_id uuid REFERENCES public.distribution_deliveries(id) ON DELETE CASCADE,
  queue_id uuid REFERENCES public.distribution_queue(id) ON DELETE CASCADE,
  title_id uuid REFERENCES public.content_titles(id) ON DELETE CASCADE,
  level text NOT NULL DEFAULT 'info', -- info | warn | error
  stage text NOT NULL,                -- packaging | mapping | connect | transfer | ack | retry
  message text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  correlation_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS distribution_delivery_logs_delivery_idx ON public.distribution_delivery_logs(delivery_id, created_at DESC);
CREATE INDEX IF NOT EXISTS distribution_delivery_logs_title_idx ON public.distribution_delivery_logs(title_id, created_at DESC);

GRANT SELECT ON public.distribution_delivery_logs TO authenticated;
GRANT ALL ON public.distribution_delivery_logs TO service_role;
ALTER TABLE public.distribution_delivery_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "owner or admin read logs" ON public.distribution_delivery_logs
  FOR SELECT TO authenticated USING (
    title_id IS NULL
    OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = title_id AND t.owner_user_id = auth.uid())
    OR public.has_role(auth.uid(),'admin')
    OR public.has_role(auth.uid(),'super_admin')
  );

-- ============ updated_at triggers ============
CREATE OR REPLACE FUNCTION public.tg_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END; $$;

DO $$ BEGIN
  CREATE TRIGGER trg_distribution_partners_touch BEFORE UPDATE ON public.distribution_partners
    FOR EACH ROW EXECUTE FUNCTION public.tg_touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_distribution_mappings_touch BEFORE UPDATE ON public.distribution_metadata_mappings
    FOR EACH ROW EXECUTE FUNCTION public.tg_touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_distribution_packages_touch BEFORE UPDATE ON public.distribution_packages
    FOR EACH ROW EXECUTE FUNCTION public.tg_touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_distribution_queue_touch BEFORE UPDATE ON public.distribution_queue
    FOR EACH ROW EXECUTE FUNCTION public.tg_touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_distribution_deliveries_touch BEFORE UPDATE ON public.distribution_deliveries
    FOR EACH ROW EXECUTE FUNCTION public.tg_touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============ RPC: retry failed deliveries ============
CREATE OR REPLACE FUNCTION public.retry_failed_distribution_deliveries(_title_id uuid DEFAULT NULL)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count int;
BEGIN
  IF NOT (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin')
          OR EXISTS (SELECT 1 FROM public.content_titles t WHERE t.id = _title_id AND t.owner_user_id = auth.uid())) THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  UPDATE public.distribution_queue
     SET status = 'retrying',
         attempts = 0,
         next_retry_at = now(),
         last_error = NULL,
         last_error_code = NULL
   WHERE status = 'failed'
     AND (_title_id IS NULL OR title_id = _title_id);
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.retry_failed_distribution_deliveries(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.retry_failed_distribution_deliveries(uuid) TO authenticated;
