-- Revoke EXECUTE from anon on SECURITY DEFINER helpers that should never be invoked unauthenticated.
-- Keep anon EXECUTE on screening_resolve / screening_log_event (token-based public screening viewer).

REVOKE EXECUTE ON FUNCTION public.admin_adjust_storage(uuid, storage_adjustment_type, numeric, text, timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_close_deal_memo(uuid, deal_status) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_manual_invoice(uuid, uuid, text, text, jsonb, numeric, boolean, date, text, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_screening_invite(uuid, uuid, text, text, text, uuid, uuid, uuid, timestamp with time zone, text, timestamp with time zone, boolean, integer, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_close(uuid, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_link_invoice(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_record_payment(uuid, text, text, bigint, text, text, timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_set_approval(uuid, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_upsert_delivery(uuid, uuid, text, text, text, text, timestamp with time zone, text, text, boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deal_upsert_payout(uuid, uuid, text, uuid, text, text, text, numeric, bigint, bigint, bigint, text, text, text, boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_extend_screening_invite(uuid, timestamp with time zone, text, timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_handle_title_edit_request(uuid, text, text, text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_issue_manual_invoice(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_mark_invoice_paid(uuid, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_provision_creator_plan(uuid, uuid, text, integer, timestamp with time zone, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_provision_studio_plan(uuid, uuid, text, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_screening_invite(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_manual_invoice(uuid, jsonb, numeric, boolean, date, text, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_void_manual_invoice(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.assert_storage_quota(uuid, bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_write_workspace(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_personal_workspace() FROM anon;
REVOKE EXECUTE ON FUNCTION public.creator_lock_title_on_submit(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.creator_request_title_edit(uuid, text, text, text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.deal_memo_check_conflict(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_free_tier_title_quota() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_title_lock_on_assets() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_title_lock_on_titles() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_workspace_storage_entitlement(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_accepted_agreement(uuid, legal_agreement_type) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_free_tier_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_super_admin(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_workspace_admin(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_workspace_member(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mfi_seats_taken() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sweep_manual_invoices_overdue() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sweep_screening_invites_expired() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_create_commercial_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_log_commercial_request_state() FROM anon;
REVOKE EXECUTE ON FUNCTION public.title_submission_readiness(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.title_write_allowed(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_in_banner(uuid, production_banner) FROM anon;